server:
  port: 8081
spring:
  profiles:
    active: dev
  autoconfigure:
    exclude: org.apache.rocketmq.spring.autoconfigure.RocketMQAutoConfiguration

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
