spring:
  sql:
    init:
      mode: never   # 首次启动改为 always 加载种子数据，之后改为 never
      continue-on-error: true
  data:
    redis:
      host: ${REDIS_HOST:172.22.32.238}
      port: 6379
      password: ${REDIS_PASSWORD:123456}
