server:
  port: 8082
spring:
  profiles:
    active: dev
  autoconfigure:
    exclude: org.apache.rocketmq.spring.autoconfigure.RocketMQAutoConfiguration
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding.yaml
  cache:
    type: caffeine
  data:
    redis:
      host: ${REDIS_HOST:172.22.32.238}
      port: 6379
      password: ${REDIS_PASSWORD:}
      timeout: 3s
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0

mybatis-plus:
  configuration:
    default-executor-type: simple
  mapper-locations: classpath*:/mapper/*.xml
